"""
SYNAPSE AI - Evidence Grounding & Citation Integrity Engine.
Implements:
Claim
 ↓
Evidence
 ↓
Source
 ↓
Citation

Guarantees:
- Every factual claim references supporting evidence.
- No citations can be invented (hallucinated sources are detected and rejected).
- Citations originate strictly from retrieved evidence chunks.
- Every source retains its original canonical URL.
- Support for multiple sources per claim.
- Detection of unsupported claims and claims with insufficient evidence.
- Automatic generation of the Sources section.
- End-to-end tracing: Report → Claim → Evidence → Source → URL.
"""

import json
import logging
import re
from typing import Any, Dict, List, Optional, Set, Tuple
from pydantic import BaseModel, Field

# -----------------------------
# Logger Configuration
# -----------------------------
logger = logging.getLogger("synapse.citations")
if not logger.handlers:
    handler = logging.StreamHandler()
    formatter = logging.Formatter(
        "[%(asctime)s] [%(name)s] [%(levelname)s] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S"
    )
    handler.setFormatter(formatter)
    logger.addHandler(handler)
    logger.setLevel(logging.INFO)


# -----------------------------
# Structured Models
# -----------------------------
class Source(BaseModel):
    """
    Metadata for a unique retrieved source.
    Retains canonical URL, publication date, quality metrics, and human-friendly citation number.
    """
    source_id: str
    title: str
    url: str
    domain: str
    publication_date: str = "N/A"
    retrieved_at: str
    source_number: int = 1
    source_type: str = "general"  # official|academic|news|industry|company|general|unknown
    quality_score: float = 0.5  # 0.0–1.0 deterministic composite
    quality_tier: str = "adequate"  # excellent|good|adequate|low|poor
    freshness: str = "undated"  # current|recent|aging|stale|undated

    @property
    def citation_tag(self) -> str:
        return f"[Source {self.source_number}]"


class EvidenceChunkRef(BaseModel):
    """
    Reference to a specific evidence chunk stored in ChromaDB vector store.
    """
    chunk_id: str
    source_id: str
    text: str
    similarity_score: float = 0.0
    url: str = ""
    title: str = ""


class Claim(BaseModel):
    """
    Structured factual claim generated by the Writer Agent.
    Explicitly grounded in retrieved evidence chunks and sources.
    """
    claim_id: str
    text: str
    supporting_source_ids: List[str] = Field(default_factory=list)
    evidence_chunk_ids: List[str] = Field(default_factory=list)
    confidence: float = 1.0  # 0.0 to 1.0
    verification_status: str = "grounded"  # "grounded", "insufficient_evidence", "unsupported"
    verification_notes: Optional[str] = None


class GroundedReport(BaseModel):
    """
    Full grounded research report with verified claim-evidence-source lineage.
    """
    topic: str
    claims: List[Claim] = Field(default_factory=list)
    sources: Dict[str, Source] = Field(default_factory=dict)
    evidence_chunks: Dict[str, EvidenceChunkRef] = Field(default_factory=dict)
    grounded_claims: List[Claim] = Field(default_factory=list)
    unsupported_claims: List[Claim] = Field(default_factory=list)
    insufficient_claims: List[Claim] = Field(default_factory=list)
    markdown_report: str = ""
    citation_trace: Dict[str, Any] = Field(default_factory=dict)


# -----------------------------
# Registry Builders
# -----------------------------
def build_source_registry(
    retrieved_evidence: List[Any]
) -> Tuple[Dict[str, Source], Dict[str, EvidenceChunkRef]]:
    """
    Index unique sources and evidence chunks from retrieved vector store records.
    Assigns stable human-friendly source numbers (1, 2, 3...).
    """
    sources: Dict[str, Source] = {}
    evidence_chunks: Dict[str, EvidenceChunkRef] = {}
    url_to_source_id: Dict[str, str] = {}
    source_counter = 1

    for ev in retrieved_evidence:
        # Support both RetrievedEvidence object and dict
        if hasattr(ev, "model_dump"):
            data = ev.model_dump()
        elif isinstance(ev, dict):
            data = ev
        else:
            continue

        sid = data.get("source_id") or ""
        url = data.get("url") or ""
        cid = data.get("chunk_id") or ""
        text = data.get("text") or ""
        title = data.get("title") or "Web Document"
        domain = data.get("domain") or "web"
        pub_date = data.get("publication_date") or "N/A"
        retrieved_at = data.get("retrieval_timestamp") or data.get("retrieved_at") or "N/A"
        similarity = float(data.get("similarity_score", 0.0))

        if not sid and url:
            import hashlib
            sid = hashlib.sha256(url.lower().encode("utf-8")).hexdigest()[:16]

        if not sid:
            continue

        # Register Source if not already present
        if sid not in sources:
            sources[sid] = Source(
                source_id=sid,
                title=title,
                url=url,
                domain=domain,
                publication_date=pub_date,
                retrieved_at=retrieved_at,
                source_number=source_counter,
            )
            url_to_source_id[url.lower()] = sid
            source_counter += 1

        # Register Evidence Chunk
        if cid:
            evidence_chunks[cid] = EvidenceChunkRef(
                chunk_id=cid,
                source_id=sid,
                text=text,
                similarity_score=similarity,
                url=url,
                title=title,
            )

    return sources, evidence_chunks


def format_evidence_catalog_for_writer(
    sources: Dict[str, Source],
    evidence_chunks: Dict[str, EvidenceChunkRef]
) -> str:
    """
    Format a structured, unambiguous evidence catalog for the Writer LLM.
    Explicitly labels valid Source IDs, Source Numbers, and Chunk IDs.
    """
    if not sources:
        return "No verified sources available in evidence store."

    lines = [
        "============================================================",
        "AUTHORITATIVE EVIDENCE CATALOG (ONLY CITE THESE VALID SOURCES)",
        "============================================================",
    ]

    for sid, src in sources.items():
        lines.append(f"\n[Source {src.source_number}] (source_id: '{sid}')")
        lines.append(f"Title: {src.title}")
        lines.append(f"URL: {src.url} | Domain: {src.domain} | Published: {src.publication_date}")
        lines.append("Supporting Evidence Chunks:")

        src_chunks = [c for c in evidence_chunks.values() if c.source_id == sid]
        if not src_chunks:
            lines.append("  (No specific chunk excerpts)")
        for chunk in src_chunks:
            lines.append(f"  - Chunk ID: '{chunk.chunk_id}' (Relevance: {chunk.similarity_score})")
            clean_excerpt = chunk.text.replace("\n", " ").strip()
            lines.append(f"    Excerpt: \"{clean_excerpt}\"")

    lines.append("\n============================================================")
    return "\n".join(lines)


# -----------------------------
# Claim Verification & Grounding Engine
# -----------------------------
def verify_claim(
    claim: Claim,
    sources: Dict[str, Source],
    evidence_chunks: Dict[str, EvidenceChunkRef]
) -> Claim:
    """
    Verify claim grounding against the evidence store:
    1. Rejects invented / hallucinated sources and chunk IDs.
    2. Validates that referenced chunks belong to the referenced sources.
    3. Checks text overlap and semantic grounding.
    4. Sets status to 'grounded', 'insufficient_evidence', or 'unsupported'.
    """
    # 1. Check for invented / non-existent sources
    valid_source_ids = [sid for sid in claim.supporting_source_ids if sid in sources]
    invalid_source_ids = [sid for sid in claim.supporting_source_ids if sid not in sources]

    # Also resolve any source referenced by chunk if source_id was omitted
    valid_chunk_ids = [cid for cid in claim.evidence_chunk_ids if cid in evidence_chunks]
    invalid_chunk_ids = [cid for cid in claim.evidence_chunk_ids if cid not in evidence_chunks]

    for cid in valid_chunk_ids:
        chunk_obj = evidence_chunks[cid]
        if chunk_obj.source_id in sources and chunk_obj.source_id not in valid_source_ids:
            valid_source_ids.append(chunk_obj.source_id)

    # If all sources were invented or no sources provided
    if not valid_source_ids and not valid_chunk_ids:
        claim.verification_status = "unsupported"
        if invalid_source_ids or invalid_chunk_ids:
            claim.verification_notes = (
                f"Invented citation detected. Cited sources {invalid_source_ids} and "
                f"chunks {invalid_chunk_ids} do not exist in the evidence store."
            )
        else:
            claim.verification_notes = "No supporting evidence or source provided."
        claim.confidence = min(claim.confidence, 0.2)
        return claim

    # If some cited sources were invented
    if invalid_source_ids or invalid_chunk_ids:
        logger.warning(
            "Claim '%s' cited invalid sources %s or chunks %s. Filtering to verified evidence.",
            claim.claim_id, invalid_source_ids, invalid_chunk_ids
        )
        claim.supporting_source_ids = valid_source_ids
        claim.evidence_chunk_ids = valid_chunk_ids

    # 2. Check grounding evidence text
    supporting_texts = []
    for cid in valid_chunk_ids:
        supporting_texts.append(evidence_chunks[cid].text)

    # If chunks not explicitly given, collect texts from valid sources
    if not supporting_texts:
        for sid in valid_source_ids:
            for c in evidence_chunks.values():
                if c.source_id == sid:
                    supporting_texts.append(c.text)

    combined_evidence = " ".join(supporting_texts).lower()

    if not combined_evidence:
        claim.verification_status = "insufficient_evidence"
        claim.verification_notes = "Referenced source has empty evidence text in the store."
        claim.confidence = min(claim.confidence, 0.4)
        return claim

    # Heuristic textual grounding check: significant words in claim must appear in evidence
    claim_words = re.findall(r"\b[a-zA-Z0-9_-]{3,}\b", claim.text.lower())
    stop_words = {
        "the", "and", "for", "with", "that", "this", "from", "are", "was", "were",
        "has", "have", "had", "will", "can", "could", "should", "would", "about",
        "into", "over", "such", "than", "then", "more", "most", "been", "also"
    }
    significant_words = [w for w in claim_words if w not in stop_words]

    if not significant_words:
        claim.verification_status = "grounded"
        return claim

    overlap_count = sum(1 for w in significant_words if w in combined_evidence)
    overlap_ratio = overlap_count / len(significant_words)

    # Numeric/quantitative factual check: if numbers are in the claim, check if they exist in evidence
    claim_numbers = re.findall(r"\b\d+(?:\.\d+)?%?\b", claim.text)
    number_match = True
    if claim_numbers:
        number_match = any(num.lower() in combined_evidence for num in claim_numbers)

    if overlap_ratio >= 0.35 and number_match:
        claim.verification_status = "grounded"
        claim.verification_notes = f"Verified: {overlap_count}/{len(significant_words)} key terms and metrics grounded in evidence."
    elif overlap_ratio >= 0.20:
        claim.verification_status = "insufficient_evidence"
        claim.verification_notes = (
            f"Insufficient evidence: only {overlap_count}/{len(significant_words)} terms matched in cited excerpts. "
            "Claim may contain unverified extrapolations."
        )
        claim.confidence = min(claim.confidence, 0.5)
    else:
        claim.verification_status = "unsupported"
        claim.verification_notes = (
            f"Unsupported: Low grounding overlap ({overlap_count}/{len(significant_words)} terms). "
            "Evidence does not substantiate this claim."
        )
        claim.confidence = min(claim.confidence, 0.3)

    return claim


def verify_all_claims(
    claims: List[Claim],
    sources: Dict[str, Source],
    evidence_chunks: Dict[str, EvidenceChunkRef]
) -> Tuple[List[Claim], List[Claim], List[Claim]]:
    """
    Verify all claims and partition into (grounded, insufficient, unsupported).
    """
    grounded: List[Claim] = []
    insufficient: List[Claim] = []
    unsupported: List[Claim] = []

    for c in claims:
        verified_c = verify_claim(c, sources, evidence_chunks)
        if verified_c.verification_status == "grounded":
            grounded.append(verified_c)
        elif verified_c.verification_status == "insufficient_evidence":
            insufficient.append(verified_c)
        else:
            unsupported.append(verified_c)

    return grounded, insufficient, unsupported


# -----------------------------
# Lineage Tracing: Report → Claim → Evidence → Source → URL
# -----------------------------
def trace_claim_lineage(
    claim: Claim,
    sources: Dict[str, Source],
    evidence_chunks: Dict[str, EvidenceChunkRef]
) -> Dict[str, Any]:
    """
    Trace the complete provenance chain for a single claim:
    Claim → Evidence Chunks → Sources → Canonical URLs.
    """
    evidence_chain = []

    # Collect all chunks cited or belonging to cited sources
    relevant_chunks = []
    for cid in claim.evidence_chunk_ids:
        if cid in evidence_chunks:
            relevant_chunks.append(evidence_chunks[cid])

    if not relevant_chunks:
        for sid in claim.supporting_source_ids:
            for c in evidence_chunks.values():
                if c.source_id == sid:
                    relevant_chunks.append(c)

    for ch in relevant_chunks:
        src = sources.get(ch.source_id)
        evidence_chain.append({
            "chunk_id": ch.chunk_id,
            "excerpt": ch.text[:250],
            "similarity_score": ch.similarity_score,
            "source": {
                "source_id": src.source_id if src else ch.source_id,
                "title": src.title if src else ch.title,
                "url": src.url if src else ch.url,
                "domain": src.domain if src else "web",
                "publication_date": src.publication_date if src else "N/A",
                "retrieved_at": src.retrieved_at if src else "N/A",
                "source_number": src.source_number if src else 0,
                "citation_tag": src.citation_tag if src else "[Source]",
            }
        })

    # Also list any source without explicit chunk
    for sid in claim.supporting_source_ids:
        if not any(ec["source"]["source_id"] == sid for ec in evidence_chain):
            src = sources.get(sid)
            if src:
                evidence_chain.append({
                    "chunk_id": "document_level",
                    "excerpt": "(Full source referenced)",
                    "similarity_score": 1.0,
                    "source": {
                        "source_id": src.source_id,
                        "title": src.title,
                        "url": src.url,
                        "domain": src.domain,
                        "publication_date": src.publication_date,
                        "retrieved_at": src.retrieved_at,
                        "source_number": src.source_number,
                        "citation_tag": src.citation_tag,
                    }
                })

    return {
        "claim_id": claim.claim_id,
        "claim_text": claim.text,
        "confidence": claim.confidence,
        "verification_status": claim.verification_status,
        "verification_notes": claim.verification_notes,
        "evidence_chain": evidence_chain,
    }


def trace_report_lineage(
    claims: List[Claim],
    sources: Dict[str, Source],
    evidence_chunks: Dict[str, EvidenceChunkRef]
) -> Dict[str, Any]:
    """
    Produce comprehensive audit trace for the entire report.
    """
    traces = [trace_claim_lineage(c, sources, evidence_chunks) for c in claims]
    grounded_count = sum(1 for c in claims if c.verification_status == "grounded")
    insufficient_count = sum(1 for c in claims if c.verification_status == "insufficient_evidence")
    unsupported_count = sum(1 for c in claims if c.verification_status == "unsupported")

    return {
        "total_claims": len(claims),
        "grounded_claims": grounded_count,
        "insufficient_claims": insufficient_count,
        "unsupported_claims": unsupported_count,
        "grounding_ratio": round(grounded_count / max(1, len(claims)), 3),
        "claims_trace": traces,
    }


# -----------------------------
# Automated Sources Section Generator
# -----------------------------
def generate_sources_section(
    sources: Dict[str, Source],
    cited_source_ids: Optional[Set[str]] = None
) -> str:
    """
    Generate an authoritative '# Sources' section automatically.
    Preserves original canonical URLs, publication dates, and domains.
    """
    if not sources:
        return "# Sources\n\nNo verified external sources were cited."

    # If specific cited sources provided, filter; otherwise list all active sources
    target_sources = (
        [s for s in sources.values() if s.source_id in cited_source_ids]
        if cited_source_ids
        else list(sources.values())
    )

    if not target_sources:
        target_sources = list(sources.values())

    # Sort by source_number
    target_sources.sort(key=lambda s: s.source_number)

    lines = ["# Sources\n"]
    for s in target_sources:
        pub_str = f" | Published: {s.publication_date}" if s.publication_date and s.publication_date != "N/A" else ""
        lines.append(
            f"- **[{s.source_number}]** [{s.title}]({s.url}) — *{s.domain}*{pub_str}"
        )

    return "\n".join(lines)


# -----------------------------
# Report Assembly
# -----------------------------
def format_claim_citation_tags(claim: Claim, sources: Dict[str, Source]) -> str:
    """
    Generate formatted in-text citations like '[Source 1]' or '[Source 1, Source 2]'.
    """
    source_nums = []
    for sid in claim.supporting_source_ids:
        if sid in sources:
            source_nums.append(str(sources[sid].source_number))

    # Also resolve from chunks
    for cid in claim.evidence_chunk_ids:
        # Check if chunk contains source ID
        for s in sources.values():
            if s.source_id in cid and str(s.source_number) not in source_nums:
                source_nums.append(str(s.source_number))

    if not source_nums:
        return ""

    sorted_nums = sorted(list(set(source_nums)), key=lambda x: int(x) if x.isdigit() else 999)
    if len(sorted_nums) == 1:
        return f"[Source {sorted_nums[0]}]"
    return f"[{', '.join(f'Source {n}' for n in sorted_nums)}]"


def _sanitize_report_text(text: str, fallback_topic: str) -> str:
    """Strip JSON artifacts, binary garbage, and ensure clean prose output for report sections."""
    if not text or not text.strip():
        return f"This report synthesizes verified empirical research on {fallback_topic}."

    cleaned = text.strip()

    # If the entire summary is a JSON object, extract the summary value
    if cleaned.startswith("{") and cleaned.endswith("}"):
        try:
            data = json.loads(cleaned)
            if isinstance(data, dict):
                cleaned = data.get("summary", "") or data.get("introduction", "") or ""
        except Exception:
            pass

    # Strip any remaining JSON syntax fragments
    cleaned = re.sub(r'^\s*\{.*?"summary"\s*:\s*"?', '', cleaned)
    cleaned = re.sub(r'"?\s*,\s*"claims"\s*:.*$', '', cleaned, flags=re.DOTALL)
    cleaned = re.sub(r'^\s*"', '', cleaned)
    cleaned = re.sub(r'"\s*$', '', cleaned)

    # Remove non-printable characters (binary corruption)
    cleaned = ''.join(ch for ch in cleaned if ch.isprintable() or ch in '\n\r\t ')
    cleaned = re.sub(r'\s+', ' ', cleaned).strip()

    if len(cleaned) < 20:
        return f"This report synthesizes verified empirical research on {fallback_topic}."

    return cleaned


def assemble_grounded_report(
    topic: str,
    summary: str,
    claims: List[Claim],
    conclusion: str,
    sources: Dict[str, Source],
    evidence_chunks: Dict[str, EvidenceChunkRef]
) -> GroundedReport:
    """
    Synthesize complete executive report with:
    - # Introduction
    - # Key Findings (Explicitly cited claims)
    - # Evidence & Grounding Audit
    - # Conclusion
    - # Sources (Automatic authoritative references)
    """
    grounded, insufficient, unsupported = verify_all_claims(claims, sources, evidence_chunks)
    trace = trace_report_lineage(claims, sources, evidence_chunks)

    # Collect cited source IDs to highlight in references
    cited_source_ids = set()
    for c in claims:
        for sid in c.supporting_source_ids:
            if sid in sources:
                cited_source_ids.add(sid)

    report_sections = [
        f"# Research Report: {topic}\n",
        "## Introduction",
        _sanitize_report_text(summary, topic),
        "\n## Key Findings\n",
    ]

    finding_num = 1
    for c in claims:
        # Skip claims with binary/corrupted text
        claim_text = c.text.strip()
        if len(claim_text) < 20:
            continue
        printable_ratio = sum(1 for ch in claim_text if ch.isprintable()) / max(1, len(claim_text))
        if printable_ratio < 0.85:
            continue

        cit_tag = format_claim_citation_tags(c, sources)
        cit_suffix = f" {cit_tag}" if cit_tag else ""

        # If unsupported or insufficient, add grounding badge in text
        status_note = ""
        if c.verification_status == "insufficient_evidence":
            status_note = " *(Note: Partial evidence support)*"
        elif c.verification_status == "unsupported":
            status_note = " *(Note: Unsubstantiated by evidence store)*"

        report_sections.append(f"{finding_num}. **{claim_text}**{cit_suffix}{status_note}\n")
        finding_num += 1

    # Conclusion
    report_sections.append("## Conclusion")
    report_sections.append(
        _sanitize_report_text(conclusion, topic) if conclusion
        else f"Strategic decision-making regarding {topic} requires ongoing empirical observation."
    )
    report_sections.append("")

    # Automatic Sources Section
    sources_sec = generate_sources_section(sources, cited_source_ids=cited_source_ids or None)
    report_sections.append(sources_sec)

    full_markdown = "\n".join(report_sections)

    return GroundedReport(
        topic=topic,
        claims=claims,
        sources=sources,
        evidence_chunks=evidence_chunks,
        grounded_claims=grounded,
        unsupported_claims=unsupported,
        insufficient_claims=insufficient,
        markdown_report=full_markdown,
        citation_trace=trace,
    )


# -----------------------------
# Parser for LLM Structured Output
# -----------------------------
def parse_writer_claims_response(
    raw_output: str,
    sources: Dict[str, Source],
    evidence_chunks: Dict[str, EvidenceChunkRef]
) -> Tuple[str, List[Claim], str]:
    """
    Robust parser for Writer Agent output.
    Extracts summary, structured claims, and conclusion.
    Handles JSON blocks, code fences, and fallback text formats.
    """
    summary = ""
    conclusion = ""
    claims: List[Claim] = []

    # 1. Attempt JSON parsing
    cleaned = raw_output.strip()
    json_candidate = None

    if "```json" in cleaned:
        m = re.search(r"```json\s*(\{.*?\})\s*```", cleaned, re.DOTALL)
        if m:
            json_candidate = m.group(1)
    elif "```" in cleaned:
        m = re.search(r"```\s*(\{.*?\})\s*```", cleaned, re.DOTALL)
        if m:
            json_candidate = m.group(1)
    elif cleaned.startswith("{") and cleaned.endswith("}"):
        json_candidate = cleaned
    else:
        # Search for first opening { and matching closing }
        start = cleaned.find("{")
        end = cleaned.rfind("}")
        if start != -1 and end != -1 and end > start:
            json_candidate = cleaned[start:end + 1]

    if json_candidate:
        try:
            data = json.loads(json_candidate)
            summary = data.get("summary") or data.get("introduction", "")
            conclusion = data.get("conclusion", "")
            raw_claims = data.get("claims", [])

            for idx, rc in enumerate(raw_claims, 1):
                if isinstance(rc, dict):
                    cid = rc.get("claim_id") or f"claim_{idx}"
                    text = rc.get("text") or rc.get("claim") or ""
                    src_ids = rc.get("supporting_source_ids") or rc.get("sources") or []
                    chk_ids = rc.get("evidence_chunk_ids") or rc.get("chunks") or []
                    conf = float(rc.get("confidence", 1.0))

                    if isinstance(src_ids, str):
                        src_ids = [src_ids]
                    if isinstance(chk_ids, str):
                        chk_ids = [chk_ids]

                    # Map any integer source numbers to source_ids if needed
                    resolved_src_ids = []
                    for sid in src_ids:
                        sid_str = str(sid).strip()
                        # If writer wrote "Source 1" or "1"
                        num_m = re.match(r"(?:source\s*)?(\d+)", sid_str, re.IGNORECASE)
                        if num_m:
                            num = int(num_m.group(1))
                            matching_src = next((s for s in sources.values() if s.source_number == num), None)
                            if matching_src:
                                resolved_src_ids.append(matching_src.source_id)
                            else:
                                resolved_src_ids.append(sid_str)
                        else:
                            resolved_src_ids.append(sid_str)

                    if text:
                        claims.append(Claim(
                            claim_id=cid,
                            text=text,
                            supporting_source_ids=resolved_src_ids,
                            evidence_chunk_ids=[str(c) for c in chk_ids],
                            confidence=conf,
                        ))

            # Clean summary if nested JSON was passed
            if summary and isinstance(summary, str) and summary.strip().startswith("{"):
                try:
                    inner = json.loads(summary.strip())
                    if isinstance(inner, dict) and "summary" in inner:
                        summary = str(inner["summary"])
                except Exception:
                    pass

            if claims:
                logger.info("Successfully parsed %d structured claims from LLM JSON output.", len(claims))
                return summary, claims, conclusion
            else:
                # Valid JSON was parsed, but claims array was empty.
                # Generate clean grounded claims from readable evidence chunks without falling through to raw text parser
                if sources and evidence_chunks:
                    logger.info("Generating grounded claims from verified evidence catalog excerpts (clean text).")
                    for idx, (cid, chunk) in enumerate(list(evidence_chunks.items())[:5], 1):
                        if not chunk.text or "\x00" in chunk.text or len(chunk.text.strip()) < 30:
                            continue
                        clean_sentences = [
                            s.strip() for s in re.split(r"[.\n]", chunk.text)
                            if len(s.strip()) > 30 and all(ch.isprintable() or ch in " \t\n" for ch in s)
                        ]
                        if clean_sentences:
                            chosen = clean_sentences[0]
                            if not chosen.endswith("."):
                                chosen += "."
                            claims.append(Claim(
                                claim_id=f"claim_{idx}",
                                text=chosen,
                                supporting_source_ids=[chunk.source_id],
                                evidence_chunk_ids=[chunk.chunk_id],
                                confidence=0.85
                            ))
                return summary, claims, conclusion

        except Exception as e:
            logger.warning("Strict JSON parsing of writer output failed: %s. Attempting regex/partial block extraction.", str(e))
            # Try to extract summary
            summary_m = re.search(r'"summary"\s*:\s*"([^"\\]*(?:\\.[^"\\]*)*)"', json_candidate)
            if summary_m:
                summary = summary_m.group(1)
            conclusion_m = re.search(r'"conclusion"\s*:\s*"([^"\\]*(?:\\.[^"\\]*)*)"', json_candidate)
            if conclusion_m:
                conclusion = conclusion_m.group(1)

            # Extract individual claim objects
            claim_objs = re.findall(r'\{\s*"claim_id"\s*:[^}]+}', json_candidate, re.DOTALL)
            for idx, c_str in enumerate(claim_objs, 1):
                try:
                    c_data = json.loads(c_str)
                    cid = c_data.get("claim_id") or f"claim_{idx}"
                    text = c_data.get("text") or c_data.get("claim") or ""
                    src_ids = c_data.get("supporting_source_ids") or []
                    chk_ids = c_data.get("evidence_chunk_ids") or []
                    if text:
                        claims.append(Claim(
                            claim_id=cid,
                            text=text,
                            supporting_source_ids=[str(s) for s in src_ids],
                            evidence_chunk_ids=[str(c) for c in chk_ids],
                            confidence=float(c_data.get("confidence", 0.95))
                        ))
                except Exception:
                    pass

            if claims:
                logger.info("Successfully recovered %d structured claims from partial JSON extraction.", len(claims))
                return summary, claims, conclusion
            if summary:
                return summary, claims, conclusion

    # 2. Text fallback parser: Look for bullet points or numbered claims with citations
    logger.info("Using text fallback parser for writer output.")
    lines = raw_output.split("\n")
    current_section = "intro"
    intro_lines = []
    conclusion_lines = []
    claim_idx = 1

    for line in lines:
        stripped = line.strip()
        lower = stripped.lower()

        # Skip raw JSON syntax artifacts
        if stripped in ("{", "}", "```", "```json") or stripped.startswith('"summary":') or stripped.startswith('"claims":'):
            continue

        if any(h in lower for h in ["# key findings", "## key findings", "### findings", "claims:"]):
            current_section = "findings"
            continue
        elif any(h in lower for h in ["# conclusion", "## conclusion", "### conclusion"]):
            current_section = "conclusion"
            continue
        elif any(h in lower for h in ["# sources", "## sources", "# references"]):
            break

        if current_section == "intro":
            if not stripped.startswith("#") and not stripped.startswith("{") and not stripped.endswith("}"):
                intro_lines.append(stripped)
        elif current_section == "conclusion":
            if not stripped.startswith("#"):
                conclusion_lines.append(stripped)
        elif current_section == "findings":
            # Check for numbered or bullet item: "1. X increased by Y% [Source 1]"
            match = re.match(r"^(?:\d+[\.\)]|[-*])\s+(.+)$", stripped)
            if match:
                raw_text = match.group(1)
                # Extract citation tags like [Source 1] or [1]
                cited_nums = re.findall(r"\[(?:Source\s*)?(\d+)\]", raw_text, re.IGNORECASE)
                clean_claim_text = re.sub(r"\[(?:Source\s*)?\d+(?:,\s*(?:Source\s*)?\d+)*\]", "", raw_text).strip()
                # Clean markdown bold/italics wrappers
                clean_claim_text = re.sub(r"^\*\*(.*?)\*\*$", r"\1", clean_claim_text).strip()

                found_src_ids = []
                found_chunk_ids = []
                for n_str in cited_nums:
                    n = int(n_str)
                    src = next((s for s in sources.values() if s.source_number == n), None)
                    if src:
                        found_src_ids.append(src.source_id)
                        # Add first chunk of that source
                        for c in evidence_chunks.values():
                            if c.source_id == src.source_id:
                                found_chunk_ids.append(c.chunk_id)
                                break

                if clean_claim_text and len(clean_claim_text) > 15:
                    claims.append(Claim(
                        claim_id=f"claim_{claim_idx}",
                        text=clean_claim_text,
                        supporting_source_ids=found_src_ids,
                        evidence_chunk_ids=found_chunk_ids,
                        confidence=0.9 if found_src_ids else 0.4
                    ))
                    claim_idx += 1

    summary = "\n".join(intro_lines).strip()
    conclusion = "\n".join(conclusion_lines).strip()

    # If summary looks like JSON, extract plain text
    if summary.startswith("{") and '"summary"' in summary:
        m = re.search(r'"summary"\s*:\s*"([^"\\]*(?:\\.[^"\\]*)*)"', summary)
        if m:
            summary = m.group(1)

    # If still no claims extracted, create fallback claims from available sources
    if not claims and sources:
        logger.info("Generating grounded claims from evidence catalog excerpts as fallback.")
        for idx, (cid, chunk) in enumerate(list(evidence_chunks.items())[:3], 1):
            if not chunk.text or "\x00" in chunk.text:
                continue
            clean_sentences = [
                s.strip() for s in chunk.text.split(".")
                if len(s.strip()) > 20 and all(ch.isprintable() or ch in " \t\n" for ch in s)
            ]
            if clean_sentences:
                claim_text = clean_sentences[0]
                claims.append(Claim(
                    claim_id=f"claim_{idx}",
                    text=claim_text,
                    supporting_source_ids=[chunk.source_id],
                    evidence_chunk_ids=[chunk.chunk_id],
                    confidence=0.85
                ))

    return summary, claims, conclusion


def synthesize_deterministic_grounded_claims(
    topic: str,
    sources: Dict[str, Source],
    evidence_chunks: Dict[str, EvidenceChunkRef]
) -> Tuple[str, List[Claim], str]:
    """
    Deterministic synthesis of grounded claims directly from retrieved evidence chunks.
    Used as an automated fallback when LLM services are rate-limited or offline.
    Never invents facts or fabricates citations.
    """
    summary = f"Empirical synthesis of retrieved evidence regarding '{topic}' (generated via deterministic synthesis fallback)."
    conclusion = f"Analysis synthesized from {len(sources)} verified sources across available evidence chunks."
    claims: List[Claim] = []

    sorted_chunks = sorted(
        evidence_chunks.values(),
        key=lambda c: getattr(c, "similarity_score", 0.0),
        reverse=True
    )

    idx = 1
    for chunk in sorted_chunks[:6]:
        # Validate chunk text is readable before extraction
        if not chunk.text or sum(1 for ch in chunk.text[:200] if ch.isprintable()) / max(1, len(chunk.text[:200])) < 0.85:
            continue
        sentences = [
            s.strip() for s in re.split(r"[.\n]", chunk.text)
            if len(s.strip()) > 35
            and sum(1 for ch in s if ch.isprintable()) / max(1, len(s)) > 0.90
        ]
        if sentences:
            chosen_sentence = sentences[0]
            if not chosen_sentence.endswith("."):
                chosen_sentence += "."
            claims.append(Claim(
                claim_id=f"claim_{idx}",
                text=chosen_sentence,
                supporting_source_ids=[chunk.source_id],
                evidence_chunk_ids=[chunk.chunk_id],
                confidence=0.85
            ))
            idx += 1

    return summary, claims, conclusion

