"""create_workspace_schema

Revision ID: d43e43316cda
Revises: 
Create Date: 2026-09-27 13:13:01.933356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd43e43316cda'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('research_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_projects', schema=None) as batch_op:
        batch_op.create_index('ix_project_created', ['created_at'], unique=False)
        batch_op.create_index('ix_project_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_projects_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_projects_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_projects_user_id'), ['user_id'], unique=False)

    op.create_table('research_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('session_name', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('verification_iteration', sa.Integer(), nullable=False),
    sa.Column('plan_data', sa.JSON(), nullable=True),
    sa.Column('evidence_summary', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_sessions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_sessions_topic'), ['topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_sessions_verification_status'), ['verification_status'], unique=False)
        batch_op.create_index('ix_session_created', ['created_at'], unique=False)
        batch_op.create_index('ix_session_project_status', ['project_id', 'status'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('execution_time_seconds', sa.Float(), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('output_payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_status'), ['status'], unique=False)
        batch_op.create_index('ix_agentrun_created', ['created_at'], unique=False)
        batch_op.create_index('ix_agentrun_session_agent', ['session_id', 'agent_name'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('supporting_source_ids', sa.JSON(), nullable=False),
    sa.Column('evidence_chunk_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index('ix_claim_session_status', ['session_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_status'), ['status'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('score', sa.String(length=50), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('claims_count', sa.Integer(), nullable=False),
    sa.Column('sources_count', sa.Integer(), nullable=False),
    sa.Column('citation_trace', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('ix_report_session_version', ['session_id', 'version'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_is_final'), ['is_final'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_version'), ['version'], unique=False)

    op.create_table('research_queries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_type', sa.String(length=50), nullable=False),
    sa.Column('is_executed', sa.Boolean(), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_queries_query_type'), ['query_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_queries_session_id'), ['session_id'], unique=False)

    op.create_table('research_subtasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('subtask_id', sa.String(length=100), nullable=False),
    sa.Column('research_question', sa.Text(), nullable=False),
    sa.Column('search_queries', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('discovered_count', sa.Integer(), nullable=False),
    sa.Column('extracted_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_subtasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_subtasks_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_subtasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_subtasks_subtask_id'), ['subtask_id'], unique=False)
        batch_op.create_index('ix_subtask_session_id', ['session_id', 'subtask_id'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('publication_date', sa.String(length=50), nullable=False),
    sa.Column('retrieval_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('freshness', sa.String(length=50), nullable=False),
    sa.Column('freshness_days', sa.Integer(), nullable=False),
    sa.Column('authority_score', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('quality_tier', sa.String(length=50), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of', sa.String(length=100), nullable=True),
    sa.Column('subtask_id', sa.String(length=100), nullable=True),
    sa.Column('authority_indicators', sa.JSON(), nullable=False),
    sa.Column('penalties', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index('ix_source_domain', ['domain'], unique=False)
        batch_op.create_index('ix_source_session_quality', ['session_id', 'quality_score'], unique=False)
        batch_op.create_index('ix_source_session_type', ['session_id', 'source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_freshness'), ['freshness'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_is_duplicate'), ['is_duplicate'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_quality_score'), ['quality_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_quality_tier'), ['quality_tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_url'), ['url'], unique=False)

    op.create_table('evidence_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=100), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('chroma_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_chunk_session_chunkid', ['session_id', 'chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_chunks_chroma_id'), ['chroma_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_chunks_chunk_id'), ['chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_chunks_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_chunks_source_id'), ['source_id'], unique=False)

    op.create_table('claim_evidence_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_chunk_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_chunk_id'], ['evidence_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claim_evidence_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_evidence_links_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_evidence_links_evidence_chunk_id'), ['evidence_chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_evidence_links_source_id'), ['source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim_evidence_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_evidence_links_source_id'))
        batch_op.drop_index(batch_op.f('ix_claim_evidence_links_evidence_chunk_id'))
        batch_op.drop_index(batch_op.f('ix_claim_evidence_links_claim_id'))

    op.drop_table('claim_evidence_links')
    with op.batch_alter_table('evidence_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_chunks_source_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_chunks_session_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_chunks_chunk_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_chunks_chroma_id'))
        batch_op.drop_index('ix_chunk_session_chunkid')

    op.drop_table('evidence_chunks')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_url'))
        batch_op.drop_index(batch_op.f('ix_sources_source_type'))
        batch_op.drop_index(batch_op.f('ix_sources_source_id'))
        batch_op.drop_index(batch_op.f('ix_sources_session_id'))
        batch_op.drop_index(batch_op.f('ix_sources_quality_tier'))
        batch_op.drop_index(batch_op.f('ix_sources_quality_score'))
        batch_op.drop_index(batch_op.f('ix_sources_is_duplicate'))
        batch_op.drop_index(batch_op.f('ix_sources_freshness'))
        batch_op.drop_index(batch_op.f('ix_sources_domain'))
        batch_op.drop_index('ix_source_session_type')
        batch_op.drop_index('ix_source_session_quality')
        batch_op.drop_index('ix_source_domain')

    op.drop_table('sources')
    with op.batch_alter_table('research_subtasks', schema=None) as batch_op:
        batch_op.drop_index('ix_subtask_session_id')
        batch_op.drop_index(batch_op.f('ix_research_subtasks_subtask_id'))
        batch_op.drop_index(batch_op.f('ix_research_subtasks_status'))
        batch_op.drop_index(batch_op.f('ix_research_subtasks_session_id'))

    op.drop_table('research_subtasks')
    with op.batch_alter_table('research_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_queries_session_id'))
        batch_op.drop_index(batch_op.f('ix_research_queries_query_type'))

    op.drop_table('research_queries')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_version'))
        batch_op.drop_index(batch_op.f('ix_reports_title'))
        batch_op.drop_index(batch_op.f('ix_reports_session_id'))
        batch_op.drop_index(batch_op.f('ix_reports_is_final'))
        batch_op.drop_index('ix_report_session_version')

    op.drop_table('reports')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_status'))
        batch_op.drop_index(batch_op.f('ix_claims_session_id'))
        batch_op.drop_index(batch_op.f('ix_claims_claim_id'))
        batch_op.drop_index('ix_claim_session_status')

    op.drop_table('claims')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_agentrun_session_agent')
        batch_op.drop_index('ix_agentrun_created')
        batch_op.drop_index(batch_op.f('ix_agent_runs_status'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_session_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_agent_name'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('research_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_session_project_status')
        batch_op.drop_index('ix_session_created')
        batch_op.drop_index(batch_op.f('ix_research_sessions_verification_status'))
        batch_op.drop_index(batch_op.f('ix_research_sessions_topic'))
        batch_op.drop_index(batch_op.f('ix_research_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_research_sessions_project_id'))

    op.drop_table('research_sessions')
    with op.batch_alter_table('research_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_projects_user_id'))
        batch_op.drop_index(batch_op.f('ix_research_projects_title'))
        batch_op.drop_index(batch_op.f('ix_research_projects_status'))
        batch_op.drop_index('ix_project_user_status')
        batch_op.drop_index('ix_project_created')

    op.drop_table('research_projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
